# Generated by Django 3.0.6 on 2020-09-14 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GnC', '0007_auto_20200817_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmental_competencies',
            name='competency_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GnC.competency_category'),
        ),
        migrations.AlterField(
            model_name='departmental_competencies',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='departmental_goals',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
