# Generated by Django 3.0.6 on 2020-09-18 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GnC', '0009_auto_20200914_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competencies',
            name='summary',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='competency_comment',
            name='comments',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='departmental_competencies_comment',
            name='comments',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='departmental_goal_comment',
            name='comments',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='goal_comment',
            name='comments',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='goals',
            name='MID_manager_comments',
            field=models.TextField(default='NIL'),
        ),
        migrations.AlterField(
            model_name='goals',
            name='MID_user_comments',
            field=models.TextField(default='NIL'),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
