# Generated by Django 3.0.6 on 2020-09-15 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GnC', '0009_auto_20200914_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmental_goals',
            name='due',
            field=models.TimeField(),
        ),
    ]
