# Generated by Django 3.0.6 on 2020-09-09 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appraisals', '0010_auto_20200809_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraisal',
            name='status',
            field=models.CharField(choices=[('Employee', 'Employee'), ('Manager', 'Manager'), ('HR', 'HR')], max_length=50),
        ),
        migrations.AlterField(
            model_name='peerappraisal',
            name='title1',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='peerappraisal',
            name='title2',
            field=models.CharField(default='NIL', max_length=500),
        ),
        migrations.AlterField(
            model_name='peerappraisal',
            name='title3',
            field=models.CharField(default='NIL', max_length=500),
        ),
        migrations.AlterField(
            model_name='peerappraisalquestion',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
